### ISSUE TITLE
Add an cucumber html report example

### ISSUE THREAD

**Issue by igniteram** [igniteram/protractor-cucumber-typescript#1]
integrate cucumber json report and html report with the framework after fixing the definitely typed cucumber `listeners`

**Comment by mrj04** [comment]
Any plans to Integrate Json report and Html report with screenshots ? 
BDD reports using extent report 
http://extentreports.com/samples/extent-bdd.html

**Comment by igniteram** [comment]
Sure I am planning to integrate html /json  reports , You could send in a PR if you would like to?

**Comment by igniteram** [comment]
HTML reports module has been integrated as part of  https://github.com/igniteram/protractor-cucumber-typescript/pull/11 & has been merged hence closing this issue.
