### ISSUE TITLE
scenario.attach is not a function

### ISSUE THREAD

**Issue by dennyx** [igniteram/protractor-cucumber-typescript#14]
Thanks for the sharing this great project;
when i tried to start the test, get complains as below:
![image](https://cloud.githubusercontent.com/assets/8176446/24346316/52430504-1306-11e7-9b13-911b7f2d4da2.png)

 may u kindly help on it, thanks~

**Comment by igniteram** [comment]
Please share your config.js and package.json files, its always good to share these files as it would help to debug such issues !

**Comment by dennyx** [comment]
hmm.. have no update for the whole project yet

**Comment by igniteram** [comment]
ohk, so you haven't changed anything. It's strange that you are facing an issue, are you sure you got no compilation errors when you ran `npm run tsc`?

**Comment by dennyx** [comment]
no compile errors get when run command `npm run tsc`

**Comment by igniteram** [comment]
I tried just now cloning this repo afresh and everything seems to work fine! 

![testrun](https://cloud.githubusercontent.com/assets/15998104/24396229/1125740c-13c0-11e7-9942-2eb72f691ad9.PNG)

I could only suggest you should use the following version of dependencies - 

* node atleast v6.9.x
* typescript atleast v2.x
* cucumber atleast v2.x
* Latest chrome browser

Except node module & chrome browser all the above modules come with the project itself no need to install separately.

Try upgrading your node and chrome browser and run the scripts, it should certainly work!

**Comment by dennyx** [comment]
thanks for the kindly details feedback, i will do as suggested~

**Comment by igniteram** [comment]
ok I got the issue, its failing in failed scenarios, I will mark this as a bug thanks for pointing out. Soon would be providing a fix for it!

**Comment by igniteram** [comment]
Provided a fix for this issue here - https://github.com/igniteram/protractor-cucumber-typescript/pull/15
Please pull in the new changes and try it out.

**Comment by dennyx** [comment]
thanks for the great effort, everything works well now~
