### ISSUE TITLE
how could I access the world object in defineSupportCode

### ISSUE THREAD

**Issue by dennyx** [igniteram/protractor-cucumber-typescript#16]
Hihi, would like to ask a question about how to access the world object in defineSupportCode method?
I wanna to set specified report name everytime run the test, and the report name specified from --world-parameters;
while I found the world object in defineSupportCode is undefined, which is an object in After method as below:
![image](https://cloud.githubusercontent.com/assets/8176446/24577451/8470b2a8-1700-11e7-91b8-59aabf805668.png)
![image](https://cloud.githubusercontent.com/assets/8176446/24577455/957eb70c-1700-11e7-974e-7e2228aa4d17.png)

thanks~

**Comment by yogitasn** [comment]
Hi dennyx,

I have query w.r.t the above code. I know this is the implementation in Typescript using Cucumber/Protractor. I too have implemented part of the code however unable to make it work. The After hook does not seem to be called at all. Is this working for you? I am pasting below code for your reference. Am i missing anything here? any help would be appreciated
Note: The below code is placed in hooks.ts under support folder.
const Cucumber = require('cucumber');
var {defineSupportCode} = require('cucumber');
var fs = require('fs');
var Promise = require('bluebird');

defineSupportCode(function ({registerHandler, After}) {

After((scenario, done) => {
if (scenario.isFailed()) {
  return browser.takeScreenshot().then(function (result) {
    //scenario.attach(new Buffer(stream, 'base64').toString('binary'), 'image/png', callback);
    var stream = fs.createWriteStream(
      'C:\\Users\\Redirection\\XYZ\\Documents\\Screenshots\\exception.png');(Saving screenshots locally)
    stream.write(new Buffer(stream, 'base64'));
    stream.end();
    Promise.resolve(result);
  }, function (err) {
    //callback(err);
    Promise.reject(err);
  })
}

**Comment by igniteram** [comment]
Hi @yogitasn 
By looking at your code, any reason you are using bluebird promises to resolve? You see the screenshot promise is already being resolved there is no need to explicitly resolve it.

@dennyx Sorry for the late response here but I hope you have found the way to access world objects if not please refer this link - [cucumberjs-world-objects](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/world.md)

**Comment by dennyx** [comment]
hi @igniteram thanks for the kindly response, it's really helpful

**Comment by igniteram** [comment]
Closing this issue as it seems to be more of a support question !
