### ISSUE TITLE
Unable to pass the multiple scenario tags from command line

### ISSUE THREAD

**Issue by smunukuntla** [igniteram/protractor-cucumber-typescript#17]
Hi - I have setup your project and trying to executing only two specific scenarios  by passing the tags via CLI like below. But the scenarios are not getting picked up..

protractor typeScript/config/config.js --cucumberOpts.tags="@Cucumber
Scenario","@ProtractorScenario"

**Comment by igniteram** [comment]
Since cucumber 2.0, tags options have been changed, [cucumber-tag-expressions](https://docs.cucumber.io/tag-expressions/) are used now. you should be able to run the scenarios by using -
`protractor typeScript/config/config.js --cucumberOpts.tags='@CucumberScenario or @ProtractorScenario'`

**Comment by smunukuntla** [comment]
Thanks for the response @igniteram 
@smoke @demo
Scenario : One

@regression
Scenario: Two

protractor typeScript/runner.js --env=prod  --cucumberOpts.tags='(@smoke and demo) or @regression' ==> This will execute scenarios which are tagged with @regression and scenarios which are tagged with both @smoke & @demo. Am I correct @igniteram ??

**Comment by igniteram** [comment]
Yes, you are correct. Please refer the above mentioned link for more examples!

**Comment by bharathkumarQA** [comment]
Hi Ram.How to pick the same list of scenarios to run form a csv file
