### ISSUE TITLE
npm run tsc fails

### ISSUE THREAD

**Issue by HaydenMeloche** [igniteram/protractor-cucumber-typescript#26]
When running `npm run tsc` on a fresh install it fails. I believe some dependencies need to be updated?

Error dump 
C:\Users\*******\Downloads\protractor-cucumber-typescript-master>npm run tsc

node_modules/protractor/built/browser.d.ts(15,18): error TS2430: Interface 'Abst
ractExtendedWebDriver' incorrectly extends interface 'ExtendedWebDriver'.
  Types of property 'controlFlow' are incompatible.F
    Type '() => promise.ControlFlow' is not assignable to type '() => promise.Co
ntrolFlow'. Two different types with this name exist, but they are unrelated.
      Type 'promise.ControlFlow' is not assignable to type 'promise.ControlFlow'
. Two different types with this name exist, but they are unrelated.
        Types of property 'execute' are incompatible.
          Type '<T>(fn: () => T | promise.Promise<T>, opt_description?: string)
=> promise.Promise<T>' is not assignable to type '<T>(fn: () => T | promise.Prom
ise<T>, opt_description?: string) => promise.Promise<T>'. Two different types wi
th this name exist, but they are unrelated.
            Types of parameters 'fn' and 'fn' are incompatible.
              Type 'T | promise.Promise<T>' is not assignable to type 'T | promi
se.Promise<T>'. Two different types with this name exist, but they are unrelated
.
                Type 'Promise<T>' is not assignable to type 'T | Promise<T>'.
                  Type 'promise.Promise<T>' is not assignable to type 'promise.P
romise<T>'. Two different types with this name exist, but they are unrelated.
                    Types of property 'then' are incompatible.
                      Type '<R>(opt_callback?: (value: T) => R | promise.IThenab
le<R>, opt_errback?: (error: any) => any) => ...' is not assignable to type '<R>
(opt_callback?: (value: T) => R | promise.IThenable<R>, opt_errback?: (error: an
y) => any) => ...'. Two different types with this name exist, but they are unrel
ated.
                        Types of parameters 'opt_callback' and 'opt_callback' ar
e incompatible.
                          Type 'R | promise.IThenable<R>' is not assignable to t
ype 'R | promise.IThenable<R>'. Two different types with this name exist, but th
ey are unrelated.
                            Type 'IThenable<R>' is not assignable to type 'R | I
Thenable<R>'.
                              Type 'promise.IThenable<R>' is not assignable to t
ype 'promise.IThenable<R>'. Two different types with this name exist, but they a
re unrelated.
                                Types of property 'then' are incompatible.
                                  Type '<R>(opt_callback?: (value: R) => R | pro
mise.IThenable<R>, opt_errback?: (error: any) => any) => ...' is not assignable
to type '<R>(opt_callback?: (value: R) => R | promise.IThenable<R>, opt_errback?
: (error: any) => any) => ...'. Two different types with this name exist, but th
ey are unrelated.
                                    Type 'Promise<R | IThenable<R>>' is not assi
gnable to type 'Promise<R>'.
                                      Types of property 'then' are incompatible.

Type '<R>(opt_callback?: (value: R | ITh
enable<R>) => R | IThenable<R>, opt_errback?: (error: any) => a...' is not assig
nable to type '<R>(opt_callback?: (value: R) => R | IThenable<R>, opt_errback?:
(error: any) => any) => Promise<R>'.
                                          Types of parameters 'opt_callback' and
 'opt_callback' are incompatible.
                                            Types of parameters 'value' and 'val
ue' are incompatible.
                                              Type 'R | IThenable<R>' is not ass
ignable to type 'R'.
                                                Type 'IThenable<R>' is not assig
nable to type 'R'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! protractor-typescript-cucumber@2.0.0 tsc: tsc
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the protractor-typescript-cucumber@2.0.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***********\AppData\Roaming\npm-cache\_logs\2017-08-11T14_42
_22_833Z-debug.log

**Comment by igniteram** [comment]
can you please specify which node.js version you are using?

**Comment by HaydenMeloche** [comment]
@igniteram That is the issue, sorry. Work doesn't allow Node to update.
