### ISSUE TITLE
Testing URL redirects

### ISSUE THREAD

**Issue by hmajumdar** [igniteram/protractor-cucumber-typescript#27]
It would be great if you can add testing of URL redirects in your kickstarter, here is my question in stacks, any pointers would be helpful

https://stackoverflow.com/questions/45909710/redirect-url-test-using-cucumber-protractor-and-typescript

**Comment by igniteram** [comment]
Have commented in SO, I would certainly plan to add more such examples in this kickstarter! closing this issue as this is more of a support question!
