### ISSUE TITLE
Support\hooks.ts:8 function timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by akreddy28** [igniteram/protractor-cucumber-typescript#3]

**Comment by igniteram** [comment]
@akreddy28 I am not able reproduce this issue you mentioned, however it is a pretty common error you get when your page takes more than 5 secs(default cucumber time) to load. Please check your network speed or retry it.

I have also pushed a code https://github.com/igniteram/protractor-cucumber-typescript/commit/64984fbdeeeb52db7f463c675d733658955e0e01 which now adds webdriver-manager when you run the test scripts and changed the default browser to chrome! please do a fresh git pull and check!

**Comment by akreddy28** [comment]
If the network is slow then always test fails, So is there any way we can increase timeout?

**Comment by igniteram** [comment]
Yes, you can check out this - [cucumber timeouts](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md)

**Comment by igniteram** [comment]
closing this issue as it is more of a support question.
