### ISSUE TITLE
Adding a new test to the repository

### ISSUE THREAD

**Issue by zac11** [igniteram/protractor-cucumber-typescript#31]
I was able to get started with the tests and the pre-built run perfectly fine. I was trying to add a new test in the already built tests.  

I added a new `.feature` file called `angular.feature` with the following steps

`Feature: To search angular on Google`

`@AngularScenario
Scenario: Cucumber Angular search`

`Given I am on google page`
`When I type "Angular"`
`Then I click on search button`
`Then I clear the search text`

And added this as a new step definition in the `/stepdefinitions/homepage.ts` as

```

Given(/^I am on angular search results page$/,async ()=>{
    await expect(browser.getTitle()).to.eventually.equal("Angular - Google Search");
});
```

However, when I run the tests, I see only the pre-built tests are running. What additional steps do I need to add a new test to the framework??

**Comment by igniteram** [comment]
You need to compile your newly added scripts using typescript compiler `tsc`, with this project you need to invoke `npm run build` which is mentioned in package.json scripts section., which compiles the .ts files to js.
Please read the readme section - https://github.com/igniteram/protractor-cucumber-typescript#run-scripts

**Comment by KariiO** [comment]
I see that you add new tag **@AngularScenario** but in config there are only three by default:
@TypeScriptScenario or @CucumberScenario or @ProtractorScenario
Did you added that tag as well?

**Comment by zac11** [comment]
@igniteram  @KariiO I had run the `npm run build` command before running the `npm run test` command . So I compiled this before running. However, I was missing the tag `@AngularScenario` in the `config` file. 

However, I am seeing this output 

```
1) Scenario: Cucumber Angular search # features\angular.feature:4
   × Given I am on angular search result page # Yadav\Documents\protractor-cucumber-typescript-master\node_modules\cucumber\src\support_code_library_builder\define_helpers.js:90
       AssertionError
           + expected - actual

           -Google
           +Angular - Google Search

           at getBasePromise.then.then.newArgs (C:\Users\Rahul Yadav\Documents\protractor-cucumber-typescript-master\node_modules\chai-as-promised\lib\chai-as-promised.js:302:22)
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:188:7)
   - When I type "Angular" # Yadav\Documents\protractor-cucumber-typescript-master\node_modules\cucumber\src\support_code_library_builder\define_helpers.js:90
   - Then I click on search button # Yadav\Documents\protractor-cucumber-typescript-master\node_modules\cucumber\src\support_code_library_builder\define_helpers.js:90
   - Then I clear the search text # Yadav\Documents\protractor-cucumber-typescript-master\node_modules\cucumber\src\support_code_library_builder\define_helpers.js:90
   √ After # Yadav\Documents\protractor-cucumber-typescript-master\node_modules\cucumber\src\support_code_library_builder\define_helpers.js:90
```

Which means my search and clear text steps are being skipped? Why is that happening?

**Comment by igniteram** [comment]
The error says it all, it is expecting page title as `Google`  whereas actually browser is returning `Angular - Google Search`, please refer the [stepdefinitions](https://github.com/igniteram/protractor-cucumber-typescript/blob/master/stepdefinitions/homePage.ts#L14) in this project , I have written these scenarios sequentially so that they get executed successfully.

I am going ahead and closing this issue as this is more of a support question  and not an issue with the framework. Feel free to raise a new one!

**Comment by zac11** [comment]
@igniteram well, that I knew that my assertion is not coming out to be correct. However, I am not sure why. The scenario I have is the same one as you. I only want to add one more feature, where I am searching for Angular along with the use cases you'd given. However even after many tries I am not able to do so.

[Repo](https://github.com/zac11/demo-ts-cucumber) ---> I have made changes in your original repo. Can you please help me debug this.

Thanks
