### ISSUE TITLE
Add examples for using Scenario Outline with Async/Await

### ISSUE THREAD

**Issue by zac11** [igniteram/protractor-cucumber-typescript#32]
Can you add examples for using Scenario outline with async/await. I can't seem to find tutorials regarding this and when I try using async with Scenario outline, it always marks the tests as complete without executing any steps.

Thanks!

**Comment by sealofevil** [comment]
Yes, we should add this feature for typescript. I don't find any information :(

**Comment by igniteram** [comment]
Added this example and raised a PR https://github.com/igniteram/protractor-cucumber-typescript/pull/45, hence closing this issue!

**Comment by zac11** [comment]
Thanks much @igniteram.
