### ISSUE TITLE
After # support\hooks.ts:10        Error: function timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by rohitnirantar** [igniteram/protractor-cucumber-typescript#35]
Because of slow application loading my scripts are failing after 5000ms. Can you please help me to increase timeout to 20secounds for cucumber. I tried to use this:
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

but not sure how to implement this.

**Comment by igniteram** [comment]
you can either use `timeout` for individual steps or `setDefaultTimeout` for global timeout. Please refer this link - https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md

**Comment by rohitnirantar** [comment]
Timeout issue resolved after adding below code to hooks.ts

var {defineSupportCode} = require('cucumber');

defineSupportCode(function({setDefaultTimeout}) {
    setDefaultTimeout(60 * 1000);
});
