### ISSUE TITLE
Logging messages to file

### ISSUE THREAD

**Issue by rohitnirantar** [igniteram/protractor-cucumber-typescript#36]
Hello,
I am trying to implement loggin with above framework. Below code works for me when i use it in one file but if i want to implement it in clean way,can someone suggest me how can i create return object in typescript and use it in stepdefinations.

Here is working code in JS:

var log4js = require('log4js');
log4js.loadAppender('file');
log4js.addAppender(log4js.appenders.file('LogData.log'), 'logs');
var logger = log4js.getLogger('logs');
logger.debug("Some debug messages");

**Comment by igniteram** [comment]
@rohitnirantar since this is more of a support question and not an issue with the framework , closing this issue. Please raise such questions in stackoverflow so that you would get answers faster.
