### ISSUE TITLE
Change TyepScript/ to TypeScript/ in .gitignore

### ISSUE THREAD

**Issue by sanko1983** [igniteram/protractor-cucumber-typescript#38]
Change tyepScript/ to typeScript/ in .gitignore file.

Regards.

**Comment by igniteram** [comment]
yup , thanks for letting me know about the typo. I would fix it when I get time or you could send in a simple PR? 😃

**Comment by sanko1983** [comment]
Yes, no problem. I will do tomorrow :)

Alejandro Iglesias Expósito

                 <https://es.linkedin.com/in/aiglesiasexposito>


2018-01-24 15:15 GMT+01:00 Ram Pasala <notifications@github.com>:
