### ISSUE TITLE
Followed the steps mentioned but still not running

### ISSUE THREAD

**Issue by BHARATSEHRA** [igniteram/protractor-cucumber-typescript#4]
Hi igniteram,

I am new to protractor and node.js ..facing problem while setting up cucumber-html reports. Could you please help me in resolving the same.

**Comment by igniteram** [comment]
Setting up html reports is pretty straight forward, there are couple of libraries which you can opt for, currently with typescript this is limited however you can use Allure reports with regular javascript, I have setup an example repo - [protractor-cucumber-allure](https://github.com/igniteram/protractor-cucumber-allure). Closing this issue as this is more of a support question!
