### ISSUE TITLE
Hooks - After not getting executed with cucumber upgrade

### ISSUE THREAD

**Issue by PingleSneha** [igniteram/protractor-cucumber-typescript#41]
Hi. Can you please upgrade all the dev dependencies specifically cucumber and reformat the code base. I downloaded ur repo and did some enhancements to suit latest versions of dependencies and also upgraded it to work with geckodriver. Struggling to use after hook with cucumber 3.5 version.

**Comment by igniteram** [comment]
@PingleSneha 

I saw the new features of cucumber version 3.05, there are not much changes done to hooks, only pickle property has been added as an extra argument to `before/after` hooks. can you try running the hooks again and let me know what error you are facing?

**Comment by PingleSneha** [comment]
I am not getting any error but code in after Hooks is not getting called. I have simply put in console.log to check if it is getting called and executed.

**Comment by PingleSneha** [comment]
Hi @igniteram,

The code for hooks works perfectly fine with latest version of protractor as well.
There was a silly mistake i did, i had removed hooks.js from cucumber opts, hence it was not working.
