### ISSUE TITLE
How to update tags from cucumbertags from config.ts file at runtime?

### ISSUE THREAD

**Issue by atulparate** [igniteram/protractor-cucumber-typescript#46]
**QUESTION**

I want to update the config.ts file at runtime where I will be reading excel file where all features and scenarios are present with a run flag. As per the 'Y' it should update that tag attribute from the config.ts file.

Inside excel structure would be something like below,
**Run Fla | ScenarioTag
Y           | @InvalidLogin
N          | @ValidLogin
Y           | @ VerifyDashboard**

After reading above file it should update config.ts as below,
 cucumberOpts: {
        compiler: "ts:ts-node/register",
        format: "json:./reports/json/cucumber_report.json",
        require: ["../../bdd/StepDefinition/*/*.ts", "../../support/*.ts"],
        strict: true,
        tags: "@InvalidLogin or @VerifyDashboard",

Please suggest.

**Comment by vishalsangave** [comment]
Create a object of `cucumberOpts={......
tags: ""
}`
then use `cucmberOpts.tags = getTagsOption();`
This will update the tags value from the method you used.

**Comment by igniteram** [comment]
@shabfactor sorry for the late reply, you can tags in the `cucumberOpts` object, you could also pass tags through command line and write a npm script for executing those tags tests!

**Comment by igniteram** [comment]
Since this is a stale issue and more of a support question, closing this for now. Please raise a new issue if necessary!
