### ISSUE TITLE
What would be the run configuration of this project using Eclipse IDE? 

### ISSUE THREAD

**Issue by ahmedsid** [igniteram/protractor-cucumber-typescript#48]
Thanks mate for such a wonderful work!!!!!!!!

Just wanted to know if any run configuration is there by which we can launch tests under this framework using Eclipse IDE??

**Comment by igniteram** [comment]
@ahmedsid Good to hear that!, Frankly I do not use Eclipse IDE but you could get lot's of help in stackoverflow and other links on how to setup and run protractor in eclipse rest all steps are same.

Closing this issue as this is more of a support question and not an issue with the framework!
Thanks,
