### ISSUE TITLE
Need info on sharing data between steps 

### ISSUE THREAD

**Issue by Balajiiguru** [igniteram/protractor-cucumber-typescript#55]
If multiple step definition file exist and want to share data from one step to other during execution, how this can be achieved in cucumber using typescript?

**Comment by igniteram** [comment]
@Balajiiguru one way would be to declare global variables in that step definition file and pass the variables to other step definitions

**Comment by igniteram** [comment]
Since this is more of a support question and not an issue with the framework, Please ask such questions in stackoverflow to get immediate reponses. closing this issue!
