### ISSUE TITLE
I am not able to link my feature file to step_definition

### ISSUE THREAD

**Issue by PratapSingh09** [igniteram/protractor-cucumber-typescript#57]
Every time I run test with  command > npm test it gives me below error message  

1) Scenario: example01 - Test sample
   ? Given that user navigates to "blog"
       Undefined. Implement with the following snippet:

         Given('that user navigates to {string}', function (string) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

Even though the same step definition is present under step-definition class
I tried this one as well
Given(/^that user navigates to "(.*?)"$/, async (pages: string) => 
but did not recognize
Blow is my feature file scenario:
```
**Feature: Example Feature
I want to learn how to make test cases
As a user of the test automation tool
I want to run and adjust the tests below
@TypeScriptScenario
Scenario Outline: example01 - Test sample
    Given that user navigates to"<pages>"
    When he searches for"<search>"
    Then text"<expected>" should display somewhere on the page
    Examples:
    | pages|  | search      |     | expected|
    | blog |  |abnc wert |     |Getting started : eebh wewfn|**

```
I am using the typescript-cucumber-protractor framework in visual studio code.
Please help me how we can generate the step-definition of feature file with automatic regex expression in vs code(Visual studio code)

**Comment by igniteram** [comment]
@PratapSingh09 Looks like your specs location is not correct, can you please post your protractor config file as well? My guess is that there is an incorrect path of feature files in specs option.

**Comment by PratapSingh09** [comment]
@igniteram
  This is my config.ts file:

import * as path from "path";
import { browser, Config } from "protractor";
import { Reporter } from "../support/reporter";
const jsonReports = process.cwd() + "/reports/json";

export const config: Config = {

    seleniumAddress: "http://127.0.0.1:4444/wd/hub",

    SELENIUM_PROMISE_MANAGER: false,

    baseUrl: "https://www.qwer.com",

    
    capabilities: {
        browserName: "chrome",
    },

    framework: "custom",
    frameworkPath: require.resolve("protractor-cucumber-framework"),

    specs: [
        "../../features/*.feature",
    ],

    onPrepare: () => {
        browser.ignoreSynchronization = true;
        browser.manage().window().maximize();
        Reporter.createDirectory(jsonReports);
    },

    cucumberOpts: {
        compiler: "ts:ts-node/register",
        format: "json:./reports/json/cucumber_report.json",
        require: ["../../typeScript/stepdefinitions/*.js", "../../typeScript/support/*.js"],
        strict: true,
        tags: "@CucumberScenario or @ProtractorScenario or @TypeScriptScenario or @OutlineScenario",
    },

    onComplete: () => {
        Reporter.createHTMLReport();
    },
};

**Comment by igniteram** [comment]
@PratapSingh09 I think your config doesn't  have any issues, I feel it has to do with how you have written your feature file, try looking at my scenario outline example feature file and implement it . I am sure it is just an configuration issue

**Comment by PratapSingh09** [comment]
@igniteram  Sure, I will look into it again. Thanks for the pointer.
I need to ask about some implementation of page object in your framework because it also did  not work for me with fields like (ElementFinder,ElementArryFinder..etc) even though I have used same configuration as yours. 
Another issue is while running project I have run all three command in terminal seperately (npm run webdriver-start,npm run build,npm test). Is there any way to configure them in single file and run that file only?
So could you please help me with these issues.
Thanks in Advance!!!!

**Comment by igniteram** [comment]
@PratapSingh09 regarding page objects "ElementFinder, ElementArryFinder" are classes you need to import from protractor, I have shown it in this project. Not sure why you are getting issues, try re-installing protractor with correct typescript config.

your second issue regarding webdriver and npm commands, ideally you need only 2 terminals , one for webdriver and other for your npm build and test.

However as pointed out this could be an tedious process so you write a simple shell/ bash script in which you can start webdriver in background and then npm build test commands

Closing this issue as this is more of a support question, please raise such queried in stackoverflow and gitter forum of protractor. Thanks
