### ISSUE TITLE
npm test do not transpile the ts file , step mentioned "The above command would create an output folder named 'Typescript' and transpile the .ts files" not working

### ISSUE THREAD

**Issue by chit786** [igniteram/protractor-cucumber-typescript#7]
Hi,

After folowing your steps I am getting following result ;

npm test > calls the script > protractor typescript/config/config.js but it do not transpile and create the folder Typescript.

Editor : Visual studio code 
Node version : 6.9.5
Npm version : 3.10.10
tsc -v : 2.2.1

Tried on windows VM. But no success. Seem like transpiler is not working.

**Comment by chit786** [comment]
solved it! 

Should do this before tsc, seem like tsc not running anymore when defined in scripts.

npm run tsc > generates the transpiled folder
npm run test works just fine!!

good repo will try to add PR for better reports.

if you have any solution for html reports like mkolisnyk:cucumber-reporting plugin then let me know,

Thank you!

**Comment by igniteram** [comment]
@chit786 Glad it worked for you, I have been planning to integrate reports see issue https://github.com/igniteram/protractor-cucumber-typescript/issues/1 to this repo but not able to find time from my chore work activities. I would be more than happy if you could send a PR for this :+1:
